### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by peti** [yuhangwang/Files#1]
Citing from http://hydra.cryp.to/build/2020108/nixlog/1/raw:

```
Test suite hspec: RUNNING...

Heads
  heads
    returns a list top few files from many files FAILED [1]

Failures:

  test-suite/HeadsSpec.hs:10: 
  1) Heads.heads returns a list top few files from many files
       uncaught exception: IOException of type NoSuchThing (data/in/f1.txt: openFile: does not exist (No such file or directory))
```

It looks like the release tarball on Hackage is incomplete.

**Comment by yuhangwang** [comment]
Thank you for letting me know. The reason for the failure is that I forgot to declare the `data-dir` and `data-files` files in the `.cabal` file and the resulting tar file didn't have the files needed for testing. Now it should be working. Not source code changes.
